name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH Key and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: "VRnh5i4zncIFh5dD"
          SSH_HOST: "194.127.192.224"
          SSH_PORT: "22"
        run: |
          # Buat file sementara untuk kunci privat
          TEMP_KEY_FILE=$(mktemp)

          # Tulis kunci privat ke file sementara, buang karakter carriage return
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > "$TEMP_KEY_FILE"
          chmod 600 "$TEMP_KEY_FILE"

          # Verifikasi apakah kunci privat berhasil ditulis
          if [[ ! -s "$TEMP_KEY_FILE" ]]; then
              echo "Error: Kunci privat tidak dapat dibaca atau file kosong."
              cat "$TEMP_KEY_FILE"
              rm -f "$TEMP_KEY_FILE"
              exit 1
          fi

          # Cek format kunci dengan openssl untuk memastikan validitas
          openssl rsa -in "$TEMP_KEY_FILE" -check -noout
          if [[ $? -ne 0 ]]; then
              echo "Error: Format kunci SSH tidak valid."
              rm -f "$TEMP_KEY_FILE"
              exit 1
          fi

          # Coba koneksi SSH
          ssh -i "$TEMP_KEY_FILE" -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" << 'EOF'
            echo "Koneksi SSH berhasil!"
            # Tambahkan perintah deployment di sini
          EOF

          # Tangani error dari perintah SSH
          if [[ $? -ne 0 ]]; then
              echo "Error: Gagal terhubung ke server melalui SSH."
              rm -f "$TEMP_KEY_FILE"
              exit 255
          fi

          # Hapus file kunci privat sementara jika berhasil
          rm -f "$TEMP_KEY_FILE"
          echo "Deployment berhasil diselesaikan."
