name: Deploy to Server

on:
  push:
    branches:
      - main  # Jalankan hanya ketika ada push di branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: "VRnh5i4zncIFh5dD"
          SSH_HOST: "194.127.192.224"
          SSH_PORT: "22"  # Ubah port jika diperlukan
        run: |
          # Skrip deployment
          TEMP_KEY_FILE=$(mktemp)
          echo "$SSH_PRIVATE_KEY" > "$TEMP_KEY_FILE"
          chmod 600 "$TEMP_KEY_FILE"

          if [[ ! -f "$TEMP_KEY_FILE" ]]; then
              echo "Error: Gagal membuat file kunci privat sementara."
              exit 1
          fi

          ssh -i "$TEMP_KEY_FILE" -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" << 'EOF'
            echo "Koneksi SSH berhasil!"
            # Tambahkan perintah deployment di sini
          EOF

          if [[ $? -ne 0 ]]; then
              echo "Error: Gagal terhubung ke server melalui SSH."
              rm -f "$TEMP_KEY_FILE"
              exit 255
          fi

          rm -f "$TEMP_KEY_FILE"
          echo "Deployment berhasil diselesaikan."
